[package]
name = "rustTCP"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio={ version = "1.28.1", features = ["full"] }
rscam = "0.5.5"
log="0.4.14"
env_logger = "0.10.0"